// <auto-generated />
namespace DnDCharacterCreator.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Updateddbtoaddnewentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updateddbtoaddnewentity));
        
        string IMigrationMetadata.Id
        {
            get { return "202101262310556_Updated db to add new entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
