// <auto-generated />
namespace DnDCharacterCreator.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FixedIndexProblems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedIndexProblems));
        
        string IMigrationMetadata.Id
        {
            get { return "202101110116539_Fixed Index Problems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
