// <auto-generated />
namespace DnDCharacterCreator.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Addedmanytomanyrelationshipbetweencharandspell : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedmanytomanyrelationshipbetweencharandspell));
        
        string IMigrationMetadata.Id
        {
            get { return "202101150023212_Added many to many relationship between char and spell"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
